# Generated by Django 4.1.1 on 2022-10-25 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintaining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Maintaining Time')),
                ('task', models.CharField(choices=[('B', 'Blaze repairt'), ('C', 'Cut branches'), ('G', 'Garbage collecting')], default='B', max_length=1)),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.trail')),
            ],
        ),
    ]
